WITH WEATHER_CTE AS (
    SELECT 
        TIME::DATE AS WEATHER_DATE
        ,WEATHER
        ,TEMP
        ,PRESSURE
        ,HUMIDITY
        ,CLOUDS
    FROM {{ source('DEMO', 'weather') }}
), WEATHER_AGG_CTE AS (
    SELECT 
        WEATHER_DATE,
        WEATHER,
        ROUND(AVG(TEMP),2) AS AVG_TEMP,
        ROUND(AVG(PRESSURE),2) AS AVG_PRESSURE,
        ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY,
        ROUND(AVG(CLOUDS),2) AS AVG_CLOUDS
    FROM WEATHER_CTE
    GROUP BY WEATHER_DATE, WEATHER  
    QUALIFY ROW_NUMBER() OVER(PARTITION BY WEATHER_DATE ORDER BY COUNT(WEATHER) DESC)=1
)
SELECT 
* 
FROM WEATHER_AGG_CTE
ORDER BY WEATHER_DATE