WITH BIKE_CTE AS (
    SELECT 
        DISTINCT 
        START_STATION_ID    AS STATION_ID
       ,START_SATATION_NAME AS STATION_NAME
       ,START_STATION_LA    AS STATION_LA
       ,START_STATION_LON   AS STATION_LON
    FROM {{ ref('stage_bike') }}
)
SELECT 
* 
FROM BIKE_CTE
ORDER BY STATION_ID