WITH BIKE AS (
    SELECT 
        BIKE_ID,
        DATE(STARTTIME) AS TRIP_DATE,
        START_STATION_ID,
        END_STATION_ID,
        TIMESTAMPDIFF(SECOND,STARTTIME,STOPTIME) AS TRIP_DURATION_SECONDS
    FROM {{ ref('stage_bike') }}
)
SELECT 
* 
FROM BIKE